### PR TITLE
Add 'clippy' and 'rustfmt' to the build process.

### LINKED ISSUE #27: Add clippy and rust formatter
This way we won't have to care much about syntax style, because it will be done for us.

Seems very helpful for a jam.

### PR DESCRIPTION
**Pull request by Qqwy**
This ensures that on save, source files are automatically reformatted according to rustfmt rules.

Clippy warnings are shown before building. (But the build happens regardless). Besides this devs might add their own in-editor clippy config.

Clippy currently ignores the `renderer` module and its submodules, because the `grrrlib` source is included inline in that file.

It might be cleaner to separate this further (like the idea @LucvandenBrand mentioned earlier to put `grrrlib` in its own subcrate), so we truly only ignore the generated unsafe code, while still checking the main rendering logic. (Clippy complains about missing safety comments for each of the unsafe
functions :shrug: )

Fixes #27

### CODE REVIEW

**Comment by Qqwy** [comment]
The PR also enables color output for the build process. Because color is 🎉

**Review by LucvandenBrand — CHANGES_REQUESTED** [review]
I'm getting build errors I'm afraid:

```
builder_1  | error: expected one of `(`, `,`, `::`, or `=`, found `:`
builder_1  |  --> src/renderer.rs:2:15
builder_1  |   |
builder_1  | 2 | #[allow(clippy:all)]
builder_1  |   |               ^ expected one of `(`, `,`, `::`, or `=`
builder_1  | 
builder_1  | warning: unused attribute `allow`
builder_1  |  --> src/renderer.rs:2:1
builder_1  |   |
builder_1  | 2 | #[allow(clippy:all)]
builder_1  |   | ^^^^^^^^^^^^^^^^^^^^
builder_1  |   |
builder_1  | note: the built-in attribute `allow` will be ignored, since it's applied to the macro invocation `include`
builder_1  |  --> src/renderer.rs:4:1
builder_1  |   |
builder_1  | 4 | include!("renderer/grrlib.rs");
builder_1  |   | ^^^^^^^
builder_1  |   = note: `#[warn(unused_attributes)]` on by default
builder_1  | 
builder_1  | warning: `rust-wii` (bin "rust-wii") generated 2 warnings (1 duplicate)
builder_1  | error: could not compile `rust-wii` due to previous error; 2 warnings emitted
builder_1  | cp: cannot stat '/build/target/powerpc-unknown-eabi/debug/rust-wii.elf': No such file or directory
```

**Comment by Qqwy** [comment]
Thanks for keeping me sharp. After reverting the changes to before the formatting, I missed a colon it seems.

Should be fixed now

**Review by LucvandenBrand — COMMENTED** [review]
Thanks again for the fix :) 

Sorry for nitpicking, but I'm seeing this one still:

```
builder_1  | warning: `rust-wii-lib` (lib) generated 2 warnings
builder_1  | warning: unused attribute `allow`
builder_1  |  --> src/renderer.rs:1:1
builder_1  |   |
builder_1  | 1 | #[allow(clippy::all)]
builder_1  |   | ^^^^^^^^^^^^^^^^^^^^^
builder_1  |   |
builder_1  | note: the built-in attribute `allow` will be ignored, since it's applied to the macro invocation `include`
builder_1  |  --> src/renderer.rs:2:1
```
Could you have a look at that?

**Comment by LucvandenBrand** [comment]
I fixed it with the `!` you talked about, can't push because I'm being sneaky and using my work laptop.
I do get this one now too, sorry :(  . 

```
builder_1  | error[E0463]: can't find crate for `test`
builder_1  | 
builder_1  |        Fixed src/game.rs (9 fixes)
builder_1  | For more information about this error, try `rustc --explain E0463`.
builder_1  | warning: `rust-wii` (bin "rust-wii" test) generated 1 warning (1 duplicate)
builder_1  | error: could not compile `rust-wii` due to previous error; 1 warning emitted
```

**Review by LucvandenBrand — APPROVED** [review]
Yes, it works!

**Pull request merged**
