### PR TITLE
Adds infrastructure for target test suite

### PR DESCRIPTION
**Pull request by Qqwy**
Implemented as a cargo 'feature' so we can use conditional compilation to run either the normal game or the test suite, while keeping the whole `build.rs` process the same.

To run tests:
- Unset the "confirm on stop" option in Dolphin's settings (under config -> interface)
- From the command line, run `path/to/dolphin --batch --exec=./bin/boot-test.elf 2>&1 | grep "OSREPORT_HLE"`.

On success, Dolphin will quit after the test suite, and the output will be something like:

```
54:40:704 Core/HLE/HLE_OS.cpp:82 N[OSREPORT_HLE]: 80020b08->80022764| Running the target test suite...
54:40:708 Core/HLE/HLE_OS.cpp:82 N[OSREPORT_HLE]: 80020b08->8001ffc8| Running tests...
54:40:720 Core/HLE/HLE_OS.cpp:82 N[OSREPORT_HLE]: 80020b08->80021a3c| Trivial test ...
54:40:720 Core/HLE/HLE_OS.cpp:82 N[OSREPORT_HLE]: 80020b08->8000d95c| Trivial test ... ok
54:40:721 Core/HLE/HLE_OS.cpp:82 N[OSREPORT_HLE]: 80020b08->80021b60| Test run successful!
```

If there are problems, Dolphin will hang. (Unfortunately...) Output will be something like:
```
53:47:386 Core/HLE/HLE_OS.cpp:82 N[OSREPORT_HLE]: 80020b74->800227d0| Running the target test suite...
53:47:390 Core/HLE/HLE_OS.cpp:82 N[OSREPORT_HLE]: 80020b74->80020034| Running tests...
54:40:402 Core/HLE/HLE_OS.cpp:82 N[OSREPORT_HLE]: 80020b08->80021a3c| Trivial test ...
54:40:402 Core/HLE/HLE_OS.cpp:82 N[OSREPORT_HLE]: 80020b08->8000d95c| Trivial test ... ok
53:47:402 Core/HLE/HLE_OS.cpp:82 N[OSREPORT_HLE]: 80020b74->80013608| Problematic test ...
53:47:403 Core/HLE/HLE_OS.cpp:82 N[OSREPORT_HLE]: 80020b74->80020670| #######################################
53:47:404 Core/HLE/HLE_OS.cpp:82 N[OSREPORT_HLE]: 80020b74->800216b0| # <[ PANIC ]> panicked at 'assertion failed: 1 == 0', src/target_tests/mod.rs:17:9
53:47:405 Core/HLE/HLE_OS.cpp:82 N[OSREPORT_HLE]: 80020b74->800206f4| #######################################
```

### CODE REVIEW

**Comment by Qqwy** [comment]
If we want to wrap Dolphin into a test runner usable for CI, we can use the `timeout` command with it, so that when it runs longer than X seconds, it is force-killed and the exit status will be non-zero:

```
timeout 5s path/to/dolphin --batch --exec=./bin/boot-test.elf 2>&1 | grep "OSREPORT_HLE"
```

Obviously the length of the timeout will need to be made longer when the test suite becomes larger/slower.

**Comment by LucvandenBrand** [comment]
Excuse my manners, but I took the liberty to merge the latest develop changes (your caching solution) into this branch.

**Review by LucvandenBrand — CHANGES_REQUESTED** [review]
Looks very good! Again, great work :) 
Could you please update the readme with the same instructions you gave here? Then I' ll approve.

**Comment by Qqwy** [comment]
@LucvandenBrand Instructions have been added to the README 👍

**Review by LucvandenBrand — APPROVED** [review]
Lookin' good!

**Pull request merged**
